# @package _group_
common:
  fp16: true
  log_format: tqdm
  log_interval: 200
  wandb_project: transformers

checkpoint:
  no_epoch_checkpoints: false
  restore_file: "/home/jean/projects/fairseq/multirun/2022-09-16/00-07-02/0/checkpoints/checkpoint104.pt"
task:
  _name: masked_lm
  data: /home/jean/projects/fairseq/data-bin/wikitext-103
  sample_break_mode: complete
  tokens_per_sample: 512

criterion: masked_lm

dataset:
  batch_size: 16
  ignore_unused_valid_subsets: true

optimizer:
  _name: adam
  weight_decay: 0.01
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 10000

optimization:
  clip_norm: 0
  lr: [0.0005]
  max_update: 125000
  max_epoch: 200
  update_freq: [32]

model:
  _name: roberta
  max_positions: 512
  dropout: 0.1
  attention_dropout: 0.1
